a = input('Digite algo: ')
print('O tipo primitivo desse valor é', type(a))
print('Só tem espaços', a.isspace())
print('É número', a.isnumeric())
print('É alfabetico', a.isalpha())
print('Está em maisuluas', a.isupper())
print('Está em minisculas', a.islower())